quotes = [
            "Believe you can and you're halfway there.",
            "Every day may not be good... but there is something good in every day.",
            "Your present circumstances don’t determine where you can go; they merely determine where you start.",
            "Healing takes time, and that's okay.",
            "You are enough, just as you are.",
            "You alone are enough. You have nothing to prove to anybody",
            "Healing grows in honesty, openness, and the courage to speak",
            "Sometimes the people around you won't understand your journey",
        ]

follow_up_questions = {
        "Depression": [
            "Have you been feeling down or sad most of the day for over 2 weeks?",
            "Are your daily responsibilities harder to manage because of these feelings?",
            "Have you lost interest or pleasure in activities you once enjoyed, such as hobbies or socializing?",
            "Do you often feel tired or have low energy, even after resting?",
            "Are you experiencing changes in your appetite or weight (either increased or decreased)?",
            "Do you have trouble falling asleep, staying asleep, or sleeping too much?",
            "Do you find it hard to concentrate, make decisions, or stay focused?",
            "Do you feel worthless, guilty, or like a burden to others?",
            "Have you had any thoughts of self-harm or suicide?",
            "Have others noticed changes in your mood, behavior, or personality recently?"
        ],
        "Anxiety": [
            "Do you often feel nervous or on edge, even without a clear reason?",
            "Is it hard to control your worrying?",
            "Do you find it difficult to relax, even in calm situations?",
            "Does your mind often race with thoughts or jump from one worry to another?",
            "Do you experience physical symptoms like a racing heart, sweating, or shortness of breath during stressful situations?",
            "Do you avoid certain places, situations, or people because they make you anxious?",
            "Have you been experiencing trouble sleeping due to anxious thoughts or restlessness?",
            "Do small concerns often feel overwhelming or out of proportion to the situation?",
            "Do you experience muscle tension, shakiness, or stomach discomfort regularly?",
            "Has anxiety been interfering with your work, school, or relationships?"
        ],
        "Bipolar Disorder": [
            "Have you experienced extreme mood swings recently?",
            "Have these shifts affected your work, finances, or relationships?",
            "Have you had periods where you felt unusually euphoric, energetic, or overly confident without a clear reason?",
            "During these high-energy periods, did you need less sleep but still feel rested?",
            "Have you ever talked more than usual or felt your thoughts were racing?",
            "Have you made impulsive decisions during mood highs—like excessive spending, risky behaviors, or quitting responsibilities?",
            "Have there been times when you felt unusually irritable or agitated, even without provocation?",
            "Do you sometimes experience intense depressive episodes that last days or weeks?",
            "Do these mood changes come in cycles, with distinct high and low periods?",
            "Has anyone close to you noticed or expressed concern about drastic changes in your mood or behavior?"
        ],
        "Panic Disorder": [
            "Have you had multiple panic attacks over the past month?",
            "Do you avoid situations or places out of fear of having an attack?",
            "During a panic attack, do you experience a sudden surge of fear or discomfort that peaks within minutes?",
            "Do you feel symptoms like a racing heart, shortness of breath, chest pain, or dizziness during these episodes?",
            "Have you ever felt like you were losing control, going crazy, or about to die during an attack?",
            "Do these attacks seem to come out of nowhere, without a clear trigger?",
            "After an attack, do you worry intensely about when or where the next one might happen?",
            "Have panic attacks caused you to change your routine or avoid normal daily activities?",
            "Do you feel disconnected from your body or surroundings (like a sense of unreality) during these episodes?",
            "Has the fear of panic attacks impacted your work, school, or relationships?"
        ],
        "Schizophrenia": [
            "Have unusual thoughts or perceptions persisted for over a month?",
            "Have these experiences disrupted your work or personal life?",
            "Have you ever heard voices or sounds that others don’t hear?",
            "Do you sometimes believe things that others say aren't true or possible (like being watched or controlled)?",
            "Have you seen things that others don’t seem to see?",
            "Do you find it difficult to organize your thoughts or stay focused during conversations?",
            "Have you noticed a decline in motivation, interest in activities, or emotional expression?",
            "Do you sometimes feel disconnected from reality or unsure what’s real and what’s not?",
            "Have your speech patterns changed—such as speaking in ways others find hard to understand or follow?",
            "Has anyone close to you expressed concern about changes in your behavior, thinking, or emotions?"
        ],
        "Eating Disorder": [
            "Have you been concerned about food or body image for several months?",
            "Is your eating behavior affecting your health or daily functioning?",
            "Do you often feel guilty, ashamed, or anxious after eating?",
            "Have you been restricting your food intake even when you're hungry?",
            "Do you frequently check your weight, body shape, or appearance in the mirror?",
            "Have you experienced episodes of eating large amounts of food in a short time, followed by purging or extreme dieting?",
            "Do you use methods like vomiting, laxatives, or excessive exercise to control your weight?",
            "Have you noticed changes in your physical health—like fatigue, dizziness, or missed periods (for females)?",
            "Do you avoid eating around others or hide your eating habits?",
            "Do thoughts about food, weight, or body image take up a large part of your day?"
        ],
        "ADHD (Attention Deficit Hyperactivity Disorder)": [
            "Have you struggled with attention or hyperactivity since childhood?",
            "Do these difficulties impact your school, job, or daily activities?",
            "Do you often find it hard to focus on tasks, even ones that interest you?",
            "Do you frequently lose things like keys, phones, or important papers?",
            "Do you find it difficult to sit still, feeling the need to move or fidget often?",
            "Do you tend to interrupt others or speak out of turn in conversations or meetings?",
            "Do you procrastinate or struggle to complete tasks that require sustained mental effort?",
            "Are you easily distracted by sounds, people, or your own thoughts?",
            "Do you often feel restless, as if you’re driven by a motor?",
            "Do you have trouble following through on instructions or organizing activities and responsibilities?"
        ],
        "Dissociative Identity Disorder": [
            "Have you felt like multiple identities or memory gaps have persisted over weeks or months?",
            "Have these experiences disrupted your daily life or relationships?",
            "Do you sometimes feel like you're observing yourself from outside your body or that the world around you isn't real?",
            "Have you ever discovered items, messages, or drawings you don’t remember creating?",
            "Do people tell you that you’ve said or done things you don’t recall doing?",
            "Have you experienced sudden shifts in mood, behavior, or skills that feel unfamiliar to you?",
            "Do you ever lose track of time—hours or even days—with no memory of what happened?",
            "Have you noticed distinct voices, names, or identities within yourself, each with their own preferences or attitudes?",
            "Do you feel like different parts of you are in conflict or unaware of each other?",
            "Have stressful or traumatic experiences triggered sudden changes in how you think, act, or feel like yourself?"
        ],
        "Substance Use Disorder": [
            "Have you been using substances regularly for over a month?",
            "Has substance use interfered with your responsibilities or relationships?",
            "Do you find it difficult to cut down or stop using the substance, even if you want to?",
            "Have you developed a tolerance—needing more of the substance to feel the same effect?",
            "Do you experience withdrawal symptoms (e.g., anxiety, nausea, sweating, irritability) when not using the substance?",
            "Do you spend a lot of time obtaining, using, or recovering from the effects of the substance?",
            "Have you continued using the substance despite knowing it’s harming your health or well-being?",
            "Have you given up hobbies, social activities, or responsibilities because of substance use?",
            "Do you often use the substance in situations where it's physically dangerous (e.g., driving, operating machinery)?",
            "Have others expressed concern about your substance use, even if you disagreed with them?"
        ],
        "Obsessive-Compulsive Disorder (OCD)": [
            "Have your unwanted thoughts or rituals lasted more than an hour a day for over two weeks?",
            "Do they interfere with your ability to focus or get things done?",
            "Do you experience intrusive, unwanted thoughts that cause you significant anxiety or distress?",
            "Do you feel compelled to perform certain actions or rituals (like checking, cleaning, or counting) to reduce anxiety?",
            "Do you recognize that your thoughts or behaviors might be excessive or irrational, but feel unable to stop them?",
            "Do you repeat certain behaviors until they feel “just right” or complete?",
            "Have you avoided certain places, people, or activities to prevent triggering obsessive thoughts or compulsions?",
            "Do these rituals or thoughts cause you embarrassment or make you feel isolated?",
            "Do you feel a strong sense of dread or fear if you try to resist the compulsive behavior?",
            "Have these patterns changed your routine or taken control over how you go about your day?"
        ],
        "Post-Traumatic Stress Disorder (PTSD)": [
            "Have you had distressing memories or reactions for more than a month after a traumatic event?",
            "Has this trauma affected your relationships or ability to concentrate?",
            "Do you experience nightmares or flashbacks related to the traumatic event?",
            "Do you avoid places, people, or activities that remind you of the trauma?",
            "Do you feel constantly on edge, easily startled, or irritable?",
            "Have you noticed changes in your mood, such as feeling numb or detached from others?",
            "Do you have difficulty sleeping or concentrating?",
            "Do you find yourself feeling guilty or blaming yourself for what happened?",
            "Have you lost interest in activities you once enjoyed?",
            "Do you experience sudden feelings of panic or fear without a clear cause?"
        ],
        "Borderline Personality Disorder": [
            "Have your emotional struggles lasted for several months or longer?",
            "Have your intense emotions or relationships caused problems at work or home?",
            "Do you experience intense fear of abandonment or rejection?",
            "Do your relationships tend to be unstable or fluctuate between idealizing and devaluing others?",
            "Have you engaged in impulsive behaviors such as spending sprees, unsafe sex, or substance abuse?",
            "Do you have recurrent suicidal thoughts or self-harming behaviors?",
            "Do you experience rapid mood swings that can last a few hours to a few days?",
            "Do you often feel empty or like you don’t know who you are?",
            "Do you have difficulty controlling anger or experience intense episodes of anger?",
            "Have you experienced transient, stress-related paranoid thoughts or severe dissociation?"
        ],
        "Social Anxiety Disorder": [
            "Have you been avoiding social situations for six months or more?",
            "Has this anxiety made it difficult to go to work or school?",
            "Do you feel intense fear or anxiety about being judged or embarrassed in social situations?",
            "Do you worry about acting in a way that will be humiliating or embarrassing?",
            "Do you avoid speaking up or participating in group conversations?",
            "Do you experience physical symptoms like sweating, trembling, or a rapid heartbeat in social settings?",
            "Do you find it hard to make eye contact or initiate conversations?",
            "Do you fear being the center of attention?",
            "Do you replay social interactions in your mind and worry about what you said or did?",
            "Does anxiety about social situations cause you to avoid meeting new people or attending events?"
        ],
        "Generalized Anxiety Disorder (GAD)": [
            "Have you experienced excessive worry about various things for 6 months or more?",
            "Has this worry made it difficult to focus or enjoy life?",
            "Do you find it hard to control your worry even when you know it might be unrealistic?",
            "Do you often feel restless, keyed up, or on edge?",
            "Do you get easily fatigued or tired?",
            "Do you have difficulty concentrating or feel your mind going blank?",
            "Do you experience muscle tension or aches?",
            "Do you have trouble sleeping, such as difficulty falling or staying asleep, or restless, unsatisfying sleep?",
            "Do your worries interfere with your daily routines or relationships?",
            "Do you feel irritable or easily annoyed most days?"
        ],
        "Adjustment Disorder": [
            "Did your emotional symptoms begin soon after a specific stressor or change?",
            "Is the stress still affecting your ability to function or move forward?",
            "Have you experienced feelings of sadness, hopelessness, or tearfulness since the stressful event?",
            "Do you feel anxious or worried more than usual?",
            "Are you having trouble concentrating or making decisions?",
            "Have you noticed changes in your sleeping or eating habits?",
            "Do you feel overwhelmed or unable to cope with daily tasks?",
            "Have you withdrawn from friends, family, or activities you used to enjoy?",
            "Do you find yourself having frequent mood swings or irritability?",
            "Are you experiencing physical symptoms like headaches, stomachaches, or fatigue without a clear medical cause?"
        ],
        "Insomnia": [
            "Have you had trouble sleeping at least three nights a week for the past month?",
            "Does your poor sleep affect your energy or concentration during the day?",
            "Do you have difficulty falling asleep even when you feel tired?",
            "Do you wake up frequently during the night and have trouble going back to sleep?",
            "Do you wake up too early and find yourself unable to fall back asleep?",
            "Do you feel unrefreshed or tired even after a full night in bed?",
            "Do you worry or feel anxious about not getting enough sleep?",
            "Have your sleep problems caused irritability or mood changes?",
            "Do you rely on medications, alcohol, or other substances to fall asleep?",
            "Has your sleep routine changed significantly due to stress, lifestyle, or health issues?"
        ],
        "Autism Spectrum Disorder": [
            "Have you experienced social or communication challenges since early childhood?",
            "Do these challenges affect your ability to connect with others or work independently?",
            "Do you find it difficult to understand social cues like facial expressions, tone of voice, or body language?",
            "Do you prefer routines and get upset when they are disrupted?",
            "Do you have intense interests or hobbies that you focus on deeply and for long periods?",
            "Do you engage in repetitive behaviors such as hand-flapping, rocking, or repeating phrases?",
            "Do you find it challenging to start or maintain conversations with others?",
            "Do you avoid eye contact or feel uncomfortable making it?",
            "Are you highly sensitive to sensory input like lights, sounds, textures, or smells?",
            "Do you struggle to adapt to new situations or environments?"
        ],
        "Persistent Depressive Disorder": [
            "Have you felt low or hopeless for more days than not for over two years?",
            "Are these long-term feelings making everyday life harder to manage?",
            "Do you have low energy or feel tired almost every day?",
            "Do you struggle with poor appetite or tend to overeat regularly?",
            "Do you have trouble sleeping or often sleep too much?",
            "Do you experience low self-esteem or feelings of inadequacy?",
            "Do you find it hard to concentrate or make decisions?",
            "Do you feel like you've lost interest in things you used to enjoy?",
            "Have others noticed that you seem consistently down, withdrawn, or irritable?",
            "Do these symptoms feel like they’ve become a normal part of your life over time?"
        ],
        "Major Depressive Disorder": [
            "Have you felt down or unmotivated for more than two weeks?",
            "Have these feelings made it hard to complete everyday tasks?",
            "Have you lost interest or pleasure in activities you once enjoyed?",
            "Do you experience significant changes in appetite or weight?",
            "Do you have trouble sleeping or sleep much more than usual?",
            "Do you feel tired or have low energy nearly every day?",
            "Do you often feel worthless, hopeless, or excessively guilty?",
            "Do you have difficulty concentrating, thinking clearly, or making decisions?",
            "Have you had thoughts of self-harm or suicide?",
            "Have others noticed changes in your mood, behavior, or overall functioning?"
        ],
        "Separation Anxiety Disorder": [
            "Have you felt extreme distress when away from someone for over four weeks?",
            "Has this fear kept you from going places or being independent?",
            "Do you worry a lot about something bad happening to someone you're attached to?",
            "Do you feel anxious or panicked when anticipating being away from a loved one?",
            "Do you avoid sleeping away from home or without a specific person nearby?",
            "Do you experience nightmares about being separated from someone close to you?",
            "Do you have physical symptoms like headaches or stomachaches when separation occurs or is expected?",
            "Do you constantly need to know the whereabouts of the person you're attached to?",
            "Do you cling to loved ones or have difficulty being alone, even for short periods?",
            "Do you often refuse to go to school, work, or social activities due to fear of separation?"
        ],
        "Dissociative Amnesia": [
            "Has the memory loss lasted more than a few hours or days?",
            "Is it interfering with your ability to function or feel safe?",
            "Have you experienced sudden gaps in your memory that can’t be explained by normal forgetfulness?",
            "Do you have trouble remembering personal information, such as your name, address, or important life events?",
            "Have you ever found yourself in a place without knowing how you got there?",
            "Do you feel disconnected from your identity or unsure of who you are at times?",
            "Have you been told by others that you’ve done things you don’t remember?",
            "Did the memory loss begin after a stressful or traumatic event?",
            "Do you avoid thinking about or discussing certain painful events from your past?",
            "Do you feel emotionally numb or detached when trying to recall specific memories?"
        ]
    }